### ISSUE TITLE
Remove ambiguity 

### ISSUE THREAD

**Issue by saifulazad** [0PEIN0/bash-helpers#13]
What will be actual folder name 
bash-helpers or helper-scripts

very confusing indeed

**Comment by 0PEIN0** [comment]
`helper-scripts` is that place where you place your `personal.sh` bash files as well as other script that are meant to customize your local environment. And `bash-helpers` folder is actually the clone of this repository.

**Comment by 0PEIN0** [comment]
But you are right, there should be a legend for these names.

**Comment by 0PEIN0** [comment]
Added legends section for these two folders.
https://github.com/0PEIN0/bash-helpers/pull/14
